spring:
  application:
    name: auth-service



  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ashok
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: YWHx2ms0eGJhYlN6TkJqbENBblUyTktWbEZka3NaNElvNkliZlJ3czZ1skhqbdjqw
  expiration-ms: 86400000   # 1 day
server:
  port: 8081